name: Release

on:
  push:
    branches: ["main"]

env:
  PROJECT_NAME: io_scene_helldivers2

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: robinraju/release-downloader@v1.10
        with:
          repository: "microsoft/DirectXTex"
          latest: true
          fileName: "texconv.exe"
      - uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          filename: "${{env.PROJECT_NAME}}.zip"
          exclusions: "*.git*"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{env.PROJECT_NAME}}.zip"
